In [1]:
import pandas as pd

In [2]:
print("Pandas version:",pd.__version__)

Pandas version: 2.3.3

## Series

In [3]:
df=pd.Series(["ali",'ahmad','murtaza','amir','zain'],name="Name")

In [4]:
df

0        ali
1      ahmad
2    murtaza
3       amir
4       zain
Name: Name, dtype: object

In [5]:
df.loc[4]

'zain'

In [6]:
df.loc[:1]

0      ali
1    ahmad
Name: Name, dtype: object

In [7]:
df.iloc[2]

'murtaza'

In [8]:
df.info()

<class 'pandas.core.series.Series'>
RangeIndex: 5 entries, 0 to 4
Series name: Name
Non-Null Count  Dtype
--------------  -----
5 non-null      object
dtypes: object(1)
memory usage: 168.0+ bytes

In [9]:
df.describe()

count       5
unique      5
top       ali
freq        1
Name: Name, dtype: object

In [10]:
df.unique()

array(['ali', 'ahmad', 'murtaza', 'amir', 'zain'], dtype=object)

In [11]:
df.isnull().sum()

0

## DataFrame

In [12]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Ali", "Ahmed", "Sara", "  John", "Fatima", "Ali", "Ayesha", None,
             "Usman", "Zara", "Bilal", "Ahmed ", "Sana", "Hassan", "Ali",
             "Kiran", "Omar", "Fatima", "Zain", "Sara"],

    "Age": [22, 25, np.nan, 28, "23", 22, 21, 24,
            None, 26, 27, 25, "twenty", 30, 22,
            23, np.nan, 23, 29, 24],

    "City": ["Lahore", "Karachi", "lahore", "Islamabad", None, "Karachi", "Lahore", "Karachi",
             "Islamabad", "Lahore", "Karachi", "Karachi ", "Lahore", "Islamabad", "Lahore",
             "Karachi", "Lahore", "Islamabad", "Karachi", None],

    "Salary": [50000, 60000, 55000, None, 52000, 50000, "48000", 62000,
               61000, None, 58000, 60000, 57000, "65000", 50000,
               54000, None, 52000, 63000, 56000],

    "Department": ["IT", "HR", "Finance", "IT", "HR", "IT", None, "Finance",
                   "IT", "HR", "Finance", "HR", "IT", "Finance", "IT",
                   "HR", "Finance", None, "IT", "HR"]
}

df = pd.DataFrame(data)

In [13]:
df

      Name     Age       City Salary Department
0      Ali      22     Lahore  50000         IT
1    Ahmed      25    Karachi  60000         HR
2     Sara     NaN     lahore  55000    Finance
3     John      28  Islamabad   None         IT
4   Fatima      23       None  52000         HR
5      Ali      22    Karachi  50000         IT
6   Ayesha      21     Lahore  48000       None
7     None      24    Karachi  62000    Finance
8    Usman    None  Islamabad  61000         IT
9     Zara      26     Lahore   None         HR
10   Bilal      27    Karachi  58000    Finance
11  Ahmed       25   Karachi   60000         HR
12    Sana  twenty     Lahore  57000         IT
13  Hassan      30  Islamabad  65000    Finance
14     Ali      22     Lahore  50000         IT
15   Kiran      23    Karachi  54000         HR
16    Omar     NaN     Lahore   None    Finance
17  Fatima      23  Islamabad  52000       None
18    Zain      29    Karachi  63000         IT
19    Sara      24       None  56000         HR

In [14]:
df.tail(10)

      Name     Age       City Salary Department
10   Bilal      27    Karachi  58000    Finance
11  Ahmed       25   Karachi   60000         HR
12    Sana  twenty     Lahore  57000         IT
13  Hassan      30  Islamabad  65000    Finance
14     Ali      22     Lahore  50000         IT
15   Kiran      23    Karachi  54000         HR
16    Omar     NaN     Lahore   None    Finance
17  Fatima      23  Islamabad  52000       None
18    Zain      29    Karachi  63000         IT
19    Sara      24       None  56000         HR

In [15]:
df.head(10)

     Name   Age       City Salary Department
0     Ali    22     Lahore  50000         IT
1   Ahmed    25    Karachi  60000         HR
2    Sara   NaN     lahore  55000    Finance
3    John    28  Islamabad   None         IT
4  Fatima    23       None  52000         HR
5     Ali    22    Karachi  50000         IT
6  Ayesha    21     Lahore  48000       None
7    None    24    Karachi  62000    Finance
8   Usman  None  Islamabad  61000         IT
9    Zara    26     Lahore   None         HR

In [16]:
df.shape

(20, 5)

In [17]:
df[["Name","Age"]].head()

     Name  Age
0     Ali   22
1   Ahmed   25
2    Sara  NaN
3    John   28
4  Fatima   23

In [18]:
df.iloc[5]

Name              Ali
Age                22
City          Karachi
Salary          50000
Department         IT
Name: 5, dtype: object

In [19]:
df.loc[4:]

      Name     Age       City Salary Department
4   Fatima      23       None  52000         HR
5      Ali      22    Karachi  50000         IT
6   Ayesha      21     Lahore  48000       None
7     None      24    Karachi  62000    Finance
8    Usman    None  Islamabad  61000         IT
9     Zara      26     Lahore   None         HR
10   Bilal      27    Karachi  58000    Finance
11  Ahmed       25   Karachi   60000         HR
12    Sana  twenty     Lahore  57000         IT
13  Hassan      30  Islamabad  65000    Finance
14     Ali      22     Lahore  50000         IT
15   Kiran      23    Karachi  54000         HR
16    Omar     NaN     Lahore   None    Finance
17  Fatima      23  Islamabad  52000       None
18    Zain      29    Karachi  63000         IT
19    Sara      24       None  56000         HR

In [20]:
df.columns

Index(['Name', 'Age', 'City', 'Salary', 'Department'], dtype='object')

In [21]:
df.value_counts()

Name    Age     City       Salary  Department
Ali     22      Lahore     50000   IT            2
Ahmed   25      Karachi    60000   HR            1
Ahmed   25      Karachi    60000   HR            1
Ali     22      Karachi    50000   IT            1
Bilal   27      Karachi    58000   Finance       1
Hassan  30      Islamabad  65000   Finance       1
Kiran   23      Karachi    54000   HR            1
Sana    twenty  Lahore     57000   IT            1
Zain    29      Karachi    63000   IT            1
Name: count, dtype: int64

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        19 non-null     object
 1   Age         17 non-null     object
 2   City        18 non-null     object
 3   Salary      17 non-null     object
 4   Department  18 non-null     object
dtypes: object(5)
memory usage: 928.0+ bytes

In [23]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df["Salary"] = pd.to_numeric(df["Salary"], errors="coerce")

In [24]:
df["Name"] = df["Name"].str.strip()
df["City"] = df["City"].str.strip()

In [25]:
df.dtypes

Name           object
Age           float64
City           object
Salary        float64
Department     object
dtype: object

In [26]:
df.describe()

             Age        Salary
count  16.000000     17.000000
mean   24.625000  56058.823529
std     2.704934   5225.784489
min    21.000000  48000.000000
25%    22.750000  52000.000000
50%    24.000000  56000.000000
75%    26.250000  60000.000000
max    30.000000  65000.000000

In [27]:
df.isnull().sum()

Name          1
Age           4
City          2
Salary        3
Department    2
dtype: int64

In [28]:
df["Age"].fillna(df['Age'].mean,inplace=True)
df["Salary"].fillna(df['Salary'].median,inplace=True)

C:\Users\AJ007\AppData\Local\Temp\ipykernel_17528\3348922444.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '<bound method Series.mean of 0     22.0
1     25.0
2      NaN
3     28.0
4     23.0
5     22.0
6     21.0
7     24.0
8      NaN
9     26.0
10    27.0
11    25.0
12     NaN
13    30.0
14    22.0
15    23.0
16     NaN
17    23.0
18    29.0
19    24.0
Name: Age, dtype: float64>' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df["Age"].fillna(df['Age'].mean,inplace=True)
C:\Users\AJ007\AppData\Local\Temp\ipykernel_17528\3348922444.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '<bound method Series.median of 0     50000.0
1     60000.0
2     55000.0
3         NaN
4     52000.0
5     50000.0
6     48000.0
7     62000.0
8     61000.0
9         NaN
10    58000.0
11    60000.0
12    57000.0
13    65000.0
14    50000.0
15    54000.0
16        NaN
17    52000.0
18    63000.0
19    56000.0
Name: Salary, dtype: float64>' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df["Salary"].fillna(df['Salary'].median,inplace=True)

In [29]:
df["City"].fillna(df["City"].mode()[0], inplace=True)
df["Department"].fillna(df["Department"].mode()[0], inplace=True)

C:\Users\AJ007\AppData\Local\Temp\ipykernel_17528\2627897998.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["City"].fillna(df["City"].mode()[0], inplace=True)
C:\Users\AJ007\AppData\Local\Temp\ipykernel_17528\2627897998.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Department"].fillna(df["Department"].mode()[0], inplace=True)

In [30]:
df=df.drop(['Name'],axis=1)

In [31]:
df.notnull().sum()

Age           20
City          20
Salary        20
Department    20
dtype: int64

##  data set

In [32]:
import pandas as pd
import numpy as np

In [33]:
df=pd.read_csv("D:\Python programming\Data sets\data.csv")

In [34]:
df

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'     90       112       NaN
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
22        45           NaN    100       119     282.0
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

## Basic data exploration

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      31 non-null     object
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB

In [36]:
df.isnull().sum()

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    2
dtype: int64

In [37]:
df.head()

   Duration          Date  Pulse  Maxpulse  Calories
0        60  '2020/12/01'    110       130     409.1
1        60  '2020/12/02'    117       145     479.0
2        60  '2020/12/03'    103       135     340.0
3        45  '2020/12/04'    109       175     282.4
4        45  '2020/12/05'    117       148     406.0

In [38]:
df.tail()

    Duration          Date  Pulse  Maxpulse  Calories
27        60  '2020/12/27'     92       118     241.0
28        60  '2020/12/28'    103       132       NaN
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [39]:
df.columns

Index(['Duration', 'Date', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')

In [40]:
df.shape

(32, 5)

In [41]:
df.describe()

         Duration       Pulse    Maxpulse    Calories
count   32.000000   32.000000   32.000000   30.000000
mean    68.437500  103.500000  128.500000  304.680000
std     70.039591    7.832933   12.998759   66.003779
min     30.000000   90.000000  101.000000  195.100000
25%     60.000000  100.000000  120.000000  250.700000
50%     60.000000  102.500000  127.500000  291.200000
75%     60.000000  106.500000  132.250000  343.975000
max    450.000000  130.000000  175.000000  479.000000

In [42]:
df.dtypes

Duration      int64
Date         object
Pulse         int64
Maxpulse      int64
Calories    float64
dtype: object

In [43]:
df['Pulse'].max()

130

In [44]:
df['Duration'].min()

30

In [45]:
df['Calories'].mean()

304.68

##  Data cleaning

In [46]:
df['Date']=pd.to_datetime(df["Date"],format="mixed")

In [47]:
df["Date"]

0    2020-12-01
1    2020-12-02
2    2020-12-03
3    2020-12-04
4    2020-12-05
5    2020-12-06
6    2020-12-07
7    2020-12-08
8    2020-12-09
9    2020-12-10
10   2020-12-11
11   2020-12-12
12   2020-12-12
13   2020-12-13
14   2020-12-14
15   2020-12-15
16   2020-12-16
17   2020-12-17
18   2020-12-18
19   2020-12-19
20   2020-12-20
21   2020-12-21
22          NaT
23   2020-12-23
24   2020-12-24
25   2020-12-25
26   2020-12-26
27   2020-12-27
28   2020-12-28
29   2020-12-29
30   2020-12-30
31   2020-12-31
Name: Date, dtype: datetime64[ns]

In [48]:
df['Calories'].fillna(df['Calories'].mean(), inplace=True)

C:\Users\AJ007\AppData\Local\Temp\ipykernel_17528\2310167773.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Calories'].fillna(df['Calories'].mean(), inplace=True)

In [49]:
df['Calories'].isnull().sum()

0

In [85]:
print(df.duplicated().sum())

1

In [91]:
df1=df.drop_duplicates()

In [92]:
print(df1.duplicated().sum())

0

In [101]:
df1.replace((450,60),inplace=True)

C:\Users\AJ007\AppData\Local\Temp\ipykernel_17528\3458342913.py:1: FutureWarning: DataFrame.replace without 'value' and with non-dict-like 'to_replace' is deprecated and will raise in a future version. Explicitly specify the new values instead.
  df1.replace((450,60),inplace=True)

In [102]:
df1.Duration

0     60
1     60
2     60
3     45
4     45
5     45
6     45
7     45
8     30
9     30
10    30
11    30
13    30
14    30
15    30
16    30
17    30
18    45
19    45
20    45
21    45
22    45
23    45
24    45
25    45
26    45
27    45
28    45
29    45
30    45
31    45
Name: Duration, dtype: int64

In [113]:
df.isnull().sum()

Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    0
dtype: int64

In [115]:
df.dropna(subset=["Date"],inplace= True)
print(df['Date'].isnull().sum())

0

In [116]:
df["Date"] = pd.to_datetime(df["Date"], format="mixed")

In [117]:
print(df.info())
print(df.head())

<class 'pandas.core.frame.DataFrame'>
Index: 31 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  31 non-null     int64
 1   Date      31 non-null     datetime64[ns]
 2   Pulse     31 non-null     int64
 3   Maxpulse  31 non-null     int64
 4   Calories  31 non-null     float64
dtypes: datetime64[ns](1), float64(1), int64(3)
memory usage: 1.5 KB
None
   Duration       Date  Pulse  Maxpulse  Calories
0        60 2020-12-01    110       130     409.1
1        60 2020-12-02    117       145     479.0
2        60 2020-12-03    103       135     340.0
3        45 2020-12-04    109       175     282.4
4        45 2020-12-05    117       148     406.0

## Data selection section

In [118]:
df1[df1.Duration > 60]

Empty DataFrame
Columns: [Duration, Date, Pulse, Maxpulse, Calories]
Index: []

In [119]:
df1[df1.Pulse > 110]

    Duration       Date  Pulse  Maxpulse  Calories
1         60 2020-12-02    117       145     479.0
4         45 2020-12-05    117       148     406.0
23        45 2020-12-23    130       101     300.0

In [120]:
df1[df1.Calories > 350]

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
4         45 2020-12-05    117       148     406.0
6         45 2020-12-07    110       136     374.0
14        30 2020-12-14    104       132     379.3
21        45 2020-12-21    108       131     364.2
30        45 2020-12-30    102       129     380.3

In [121]:
df[(df["Pulse"] >= 100) & (df["Pulse"] <= 110)]

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130    409.10
2         60 2020-12-03    103       135    340.00
3         45 2020-12-04    109       175    282.40
5         60 2020-12-06    102       127    300.00
6         60 2020-12-07    110       136    374.00
7        450 2020-12-08    104       134    253.30
8         30 2020-12-09    109       133    195.10
10        60 2020-12-11    103       147    329.30
11        60 2020-12-12    100       120    250.70
12        60 2020-12-12    100       120    250.70
13        60 2020-12-13    106       128    345.30
14        60 2020-12-14    104       132    379.30
17        60 2020-12-17    100       120    300.00
19        60 2020-12-19    103       123    323.00
21        60 2020-12-21    108       131    364.20
24        45 2020-12-24    105       132    246.00
25        60 2020-12-25    102       126    334.50
26        60 2020-12-26    100       120    250.00
28        60 2020-12-28    103       132    304.68
29        60 2020-12-29    100       132    280.00
30        60 2020-12-30    102       129    380.30

In [112]:
df[["Duration","Calories"]].head()

   Duration  Calories
0        60     409.1
1        60     479.0
2        60     340.0
3        45     282.4
4        45     406.0

In [122]:
df["Duration"].unique()

array([ 60,  45, 450,  30], dtype=int64)

In [123]:
df["Duration"].value_counts()

Duration
60     24
45      5
450     1
30      1
Name: count, dtype: int64

In [124]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [Duration, Date, Pulse, Maxpulse, Calories]
Index: []

In [127]:
df['Pulse'].mean()

103.61290322580645

In [128]:
df.loc[df['Calories'].idxmax()]

Duration                     60
Date        2020-12-02 00:00:00
Pulse                       117
Maxpulse                    145
Calories                  479.0
Name: 1, dtype: object

In [129]:
df['Calories'].sum()

9467.76

In [130]:
df["Duration"].mean()

69.19354838709677

In [131]:
df["Maxpulse"].max()

175

In [132]:
df.corr()

          Duration      Date     Pulse  Maxpulse  Calories
Duration  1.000000 -0.139071 -0.000572  0.042271 -0.118351
Date     -0.139071  1.000000 -0.360587 -0.502902 -0.340753
Pulse    -0.000572 -0.360587  1.000000  0.269000  0.484359
Maxpulse  0.042271 -0.502902  0.269000  1.000000  0.342547
Calories -0.118351 -0.340753  0.484359  0.342547  1.000000

In [135]:
df.groupby("Duration")["Pulse"].mean()

Duration
30     109.000
45     103.600
60     103.375
450    104.000
Name: Pulse, dtype: float64

In [138]:
df.sort_values(by='Calories', ascending=False)

    Duration       Date  Pulse  Maxpulse  Calories
1         60 2020-12-02    117       145    479.00
0         60 2020-12-01    110       130    409.10
4         45 2020-12-05    117       148    406.00
30        60 2020-12-30    102       129    380.30
14        60 2020-12-14    104       132    379.30
6         60 2020-12-07    110       136    374.00
21        60 2020-12-21    108       131    364.20
13        60 2020-12-13    106       128    345.30
2         60 2020-12-03    103       135    340.00
25        60 2020-12-25    102       126    334.50
10        60 2020-12-11    103       147    329.30
19        60 2020-12-19    103       123    323.00
28        60 2020-12-28    103       132    304.68
18        45 2020-12-18     90       112    304.68
23        60 2020-12-23    130       101    300.00
5         60 2020-12-06    102       127    300.00
17        60 2020-12-17    100       120    300.00
3         45 2020-12-04    109       175    282.40
29        60 2020-12-29    100       132    280.00
15        60 2020-12-15     98       123    275.00
9         60 2020-12-10     98       124    269.00
7        450 2020-12-08    104       134    253.30
12        60 2020-12-12    100       120    250.70
11        60 2020-12-12    100       120    250.70
26        60 2020-12-26    100       120    250.00
24        45 2020-12-24    105       132    246.00
20        45 2020-12-20     97       125    243.00
31        60 2020-12-31     92       115    243.00
27        60 2020-12-27     92       118    241.00
16        60 2020-12-16     98       120    215.20
8         30 2020-12-09    109       133    195.10

In [139]:
df.sort_values(by="Pulse", ascending=True)

    Duration       Date  Pulse  Maxpulse  Calories
18        45 2020-12-18     90       112    304.68
31        60 2020-12-31     92       115    243.00
27        60 2020-12-27     92       118    241.00
20        45 2020-12-20     97       125    243.00
16        60 2020-12-16     98       120    215.20
9         60 2020-12-10     98       124    269.00
15        60 2020-12-15     98       123    275.00
29        60 2020-12-29    100       132    280.00
11        60 2020-12-12    100       120    250.70
12        60 2020-12-12    100       120    250.70
17        60 2020-12-17    100       120    300.00
26        60 2020-12-26    100       120    250.00
30        60 2020-12-30    102       129    380.30
5         60 2020-12-06    102       127    300.00
25        60 2020-12-25    102       126    334.50
10        60 2020-12-11    103       147    329.30
2         60 2020-12-03    103       135    340.00
19        60 2020-12-19    103       123    323.00
28        60 2020-12-28    103       132    304.68
7        450 2020-12-08    104       134    253.30
14        60 2020-12-14    104       132    379.30
24        45 2020-12-24    105       132    246.00
13        60 2020-12-13    106       128    345.30
21        60 2020-12-21    108       131    364.20
3         45 2020-12-04    109       175    282.40
8         30 2020-12-09    109       133    195.10
6         60 2020-12-07    110       136    374.00
0         60 2020-12-01    110       130    409.10
1         60 2020-12-02    117       145    479.00
4         45 2020-12-05    117       148    406.00
23        60 2020-12-23    130       101    300.00

In [141]:
df.groupby('Duration')['Pulse'].mean()

Duration
30     109.000
45     103.600
60     103.375
450    104.000
Name: Pulse, dtype: float64

In [142]:
df.nlargest(5,"Calories")

    Duration       Date  Pulse  Maxpulse  Calories
1         60 2020-12-02    117       145     479.0
0         60 2020-12-01    110       130     409.1
4         45 2020-12-05    117       148     406.0
30        60 2020-12-30    102       129     380.3
14        60 2020-12-14    104       132     379.3

In [143]:
df.nsmallest(5,"Calories")

    Duration       Date  Pulse  Maxpulse  Calories
8         30 2020-12-09    109       133     195.1
16        60 2020-12-16     98       120     215.2
27        60 2020-12-27     92       118     241.0
20        45 2020-12-20     97       125     243.0
31        60 2020-12-31     92       115     243.0